name: Build and Deploy

on:
  push:
    branches: [main, staging]

jobs:
  deploy:
    permissions:
      packages: write
      contents: read
    uses: b-zago/actions/.github/workflows/ghcr-rikami.yaml@v1
    with:
      image-name: webserver
    secrets: inherit
